export const localVideoWebmSources: Record<string, string> = {
  "/Showreel_SSD.mp4": "/Showreel_SSD.webm",
  "/bts_videos/IMG_1035.mp4": "/bts_videos/IMG_1035.webm",
  "/bts_videos/IMG_8338.mp4": "/bts_videos/IMG_8338.webm",
  "/bts_videos/VID_20250530_115521841.mp4": "/bts_videos/VID_20250530_115521841.webm",
  "/bts_videos/VID_20250530_170511772.mp4": "/bts_videos/VID_20250530_170511772.webm",
  "/bts_videos/VID_20250530_171117644.mp4": "/bts_videos/VID_20250530_171117644.webm",
  "/bts_videos/VID_20260223_123414583.mp4": "/bts_videos/VID_20260223_123414583.webm",
  "/bts_videos/WMN.mp4": "/bts_videos/WMN.webm",
  "/culture/Fun times_reel3.mp4": "/culture/Fun times_reel3.webm",
  "/culture/Guitar_Reel2.mp4": "/culture/Guitar_Reel2.webm",
  "/culture/Hr_reel.mp4": "/culture/Hr_reel.webm",
  "/culture/New_badminton.mp4": "/culture/New_badminton.webm",
  "/culture/Rotate_reel4.mp4": "/culture/Rotate_reel4.webm",
  "/culture/badminton_reel5.mp4": "/culture/badminton_reel5.webm",
  "/culture/cricket.mp4": "/culture/cricket.webm",
  "/culture/production head_reel5.mp4": "/culture/production head_reel5.webm",
  "/culture/reel1.mp4": "/culture/reel1.webm",
  "/culture/viral_reel3.mp4": "/culture/viral_reel3.webm",
  "/deity-video.mp4": "/deity-video.webm",
  "/home/reels/BW.mp4": "/home/reels/BW.webm",
  "/home/reels/NBS_SR.mp4": "/home/reels/NBS_SR.webm",
  "/home/works/ra_vid.mp4": "/home/works/ra_vid.webm",
  "/lyrical-video-edits/Mali Athu Beli Athu Lyrical video Title Track_ Kerebete.mp4": "/lyrical-video-edits/Mali Athu Beli Athu Lyrical video Title Track_ Kerebete.webm",
  "/lyrical-video-edits/Nooraru Rangiro - Lyrical Video.mp4": "/lyrical-video-edits/Nooraru Rangiro - Lyrical Video.webm",
  "/lyrical-video-edits/PENTAGON - Theme Lyrical Video Song.mp4": "/lyrical-video-edits/PENTAGON - Theme Lyrical Video Song.webm",
  "/lyrical-video-edits/ant_video.mp4": "/lyrical-video-edits/ant_video.webm",
  "/nearby/Nearby_studio_tour.mp4": "/nearby/Nearby_studio_tour.webm",
  "/prabhava/AA_30 Years Trailer cut V2.mp4": "/prabhava/AA_30 Years Trailer cut V2.webm",
  "/prabhava/events/45_event.mp4": "/prabhava/events/45_event.webm",
  "/prabhava/events/mk_event.mp4": "/prabhava/events/mk_event.webm",
  "/prabhava/events/yash_event.mp4": "/prabhava/events/yash_event.webm",
  "/prabhava/rishab_shetty.mp4": "/prabhava/rishab_shetty.webm",
  "/trailers/DM_trailer.mp4": "/trailers/DM_trailer.webm",
  "/trailers/Jignaasu _ Shankar Nag_Teaser.mp4": "/trailers/Jignaasu _ Shankar Nag_Teaser.webm",
  "/trailers/Mooruvare Neetigalu_Trailer.mp4": "/trailers/Mooruvare Neetigalu_Trailer.webm",
  "/video-edits/45_making.mp4": "/video-edits/45_making.webm",
  "/video-edits/Dhanya_Ramkumar.mp4": "/video-edits/Dhanya_Ramkumar.webm",
  "/video-edits/Dr.Raj_Kumar.mp4": "/video-edits/Dr.Raj_Kumar.webm",
  "/video-edits/Judgment_Birthday.mp4": "/video-edits/Judgment_Birthday.webm",
  "/video-edits/buzziwah.mp4": "/video-edits/buzziwah.webm",
  "/video-edits/ff.mp4": "/video-edits/ff.webm",
  "/video-edits/kalapathar_credits_making.mp4": "/video-edits/kalapathar_credits_making.webm",
  "/video-edits/longoti_making.mp4": "/video-edits/longoti_making.webm",
  "/video-edits/nbs.mp4": "/video-edits/nbs.webm",
  "/video-edits/rishab_shetty.mp4": "/video-edits/rishab_shetty.webm",
  "/video-edits/samrat.mp4": "/video-edits/samrat.webm",
}
